version: 0.0
os: linux
files:
  - source: /templates/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: boot.sh
      timeout: 300
      runas: root

  BeforeAllowTraffic:
    - location: start.sh
      timeout: 300
      runas: root
